apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: code-vision-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: australia-southeast1-docker.pkg.dev/PROJECT_ID/code-vision/code-vision-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: APP_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: API_VERSION
          value: "v1"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: app-secrets
  traffic:
  - percent: 100
    latestRevision: true
